# Generated by Django 4.2.23 on 2025-07-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Quiz", "0002_choice_question_quizattempt_delete_quesmodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="correct",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "A"), (2, "B"), (3, "C"), (4, "D")], default=1
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="math_2024_430_1_1_BASIC/"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="op1",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="op2",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="op3",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="op4",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="uid",
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="paper_code",
            field=models.CharField(default="30-1-1", max_length=20),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="year",
            field=models.IntegerField(default=2024),
        ),
    ]
