# Generated by Django 4.2.23 on 2025-07-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Quiz", "0003_question_correct_question_image_question_op1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
